#server:
#  port: 8088
#spring:
#  application:
#    name: application
#  profiles:
#    active: dev,db

#  rabbitmq:
#    host: 127.0.0.1
#    port: 881
#    username: root
#    password: root
#    connection-timeout: 60s
#    virtual-host: /
#    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
#    publisher-confirm-type: correlated
#    #保证交换机能把消息推送到队列中
#    publisher-returns: true
#    listener:
#      type: direct
#      direct:
#        #这个配置是保证消费者会消费消息，手动确认
#        acknowledge-mode: manual
#        prefetch: 1 #限制每次发送一条数据
#        consumers-per-queue: 10 #每个队列消费者数量
#        auto-startup: true #消费者自动启动
#        default-requeue-rejected: true #消费失败，自动重新入队
#        #发送重试策略相关配置
#        retry:
#          enabled: true #是否支持重试
#          max-attempts: 3
#          stateless: true #重试是有状态的还是无状态，既对上次重试是否有感知
#          multiplier: 1.0 #时间策略乘数因子
#          initial-interval: 1000ms
#          max-interval: 10000ms
